name: CSS build

on:
  push:
    branches:
      - main
    paths:
      - 'scss/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'scss/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  build:
    name: Build CSS
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v4.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v4.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build main CSS
        run: pnpm run css-build

      - name: Upload CSS artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.0
        with:
          name: css
          path: css/main.css
          if-no-files-found: error
